### ISSUE TITLE
Studio crashes when viewing very large files

### ISSUE THREAD

**Issue by james-whiteside** [typedb/typedb-studio#743]
## Description

Studio crashed when attempting to open a 1.9 GB TypeQL file.

## Environment

1. TypeDB version: 2.17.0
2. OS of TypeDB server: MacOS 12.6.1
3. Studio version: https://github.com/vaticle/typedb-studio/commit/6d1b4f730df08d1d96bff66a7f48f974f9088f58

## Reproducible Steps

Open a 1.9 GB TypeQL file in the text editor. Bigger files probably also work, but this is untested.

## Expected Output

File opens.

## Actual Output

```
Title: Java heap space
Trace: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:160)
	at java.base/java.lang.String.<init>(String.java:3214)
	at java.base/java.lang.String.<init>(String.java:276)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:358)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.vaticle.typedb.studio.service.project.FileState.loadBinaryFileLines(FileState.kt:219)
	at com.vaticle.typedb.studio.service.project.FileState.readContent(FileState.kt:204)
	at com.vaticle.typedb.studio.service.project.FileState.tryOpen(FileState.kt:168)
	at com.vaticle.typedb.studio.service.project.FileState.tryOpen(FileState.kt:146)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser.openPath(ProjectBrowser.kt:104)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser.access$openPath(ProjectBrowser.kt:50)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser$NavigatorLayout$navState$1$1.invoke(ProjectBrowser.kt:84)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser$NavigatorLayout$navState$1$1.invoke(ProjectBrowser.kt:84)
	at com.vaticle.typedb.studio.framework.material.Navigator$NavigatorState.open$framework_material_material(Navigator.kt:338)
	at com.vaticle.typedb.studio.framework.material.Navigator.ItemLayout_942rkJo$mayOpenItem(Navigator.kt:464)
	at com.vaticle.typedb.studio.framework.material.Navigator.access$ItemLayout_942rkJo$mayOpenItem(Navigator.kt:103)
	at com.vaticle.typedb.studio.framework.material.Navigator$ItemLayout$3.invoke(Navigator.kt:477)
	at com.vaticle.typedb.studio.framework.material.Navigator$ItemLayout$3.invoke(Navigator.kt:477)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter_skikoKt$onPointerEvent$1$1$1.invokeSuspend(SuspendingPointerInputFilter.skiko.kt:47)
	at (Coroutine boundary.()
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter_skikoKt$onPointerEvent$1$1.invokeSuspend(SuspendingPointerInputFilter.skiko.kt:43)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilterKt$pointerInput$2$2$1.invokeSuspend(SuspendingPointerInputFilter.kt:245)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringUTF16.compress(StringUTF16.java:160)
	at java.base/java.lang.String.<init>(String.java:3214)
	at java.base/java.lang.String.<init>(String.java:276)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:358)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.vaticle.typedb.studio.service.project.FileState.loadBinaryFileLines(FileState.kt:219)
	at com.vaticle.typedb.studio.service.project.FileState.readContent(FileState.kt:204)
	at com.vaticle.typedb.studio.service.project.FileState.tryOpen(FileState.kt:168)
	at com.vaticle.typedb.studio.service.project.FileState.tryOpen(FileState.kt:146)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser.openPath(ProjectBrowser.kt:104)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser.access$openPath(ProjectBrowser.kt:50)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser$NavigatorLayout$navState$1$1.invoke(ProjectBrowser.kt:84)
	at com.vaticle.typedb.studio.module.project.ProjectBrowser$NavigatorLayout$navState$1$1.invoke(ProjectBrowser.kt:84)
	at com.vaticle.typedb.studio.framework.material.Navigator$NavigatorState.open$framework_material_material(Navigator.kt:338)
	at com.vaticle.typedb.studio.framework.material.Navigator.ItemLayout_942rkJo$mayOpenItem(Navigator.kt:464)
	at com.vaticle.typedb.studio.framework.material.Navigator.access$ItemLayout_942rkJo$mayOpenItem(Navigator.kt:103)
	at com.vaticle.typedb.studio.framework.material.Navigator$ItemLayout$3.invoke(Navigator.kt:477)
	at com.vaticle.typedb.studio.framework.material.Navigator$ItemLayout$3.invoke(Navigator.kt:477)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter_skikoKt$onPointerEvent$1$1$1.invokeSuspend(SuspendingPointerInputFilter.skiko.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:569)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:459)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:472)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:285)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:272)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:272)
```

**Comment by alexjpwalker** [comment]
Fixed in Studio 3 due to not using Compose
