### ISSUE TITLE
Random crash when loading query results

### ISSUE THREAD

**Issue by james-whiteside** [typedb/typedb-studio#767]
## Description

Following crash occured part-way through receiving results from the server.

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at com.vaticle.typedb.studio.framework.graph.Viewport.nearestEdges-k-4lQ0M(Viewport.kt:177)
	at com.vaticle.typedb.studio.framework.graph.Viewport.findEdgeAt-3MmeM6k(Viewport.kt:101)
	at com.vaticle.typedb.studio.framework.graph.Interactions$HoveredObjectChecker.run(Interactions.kt:82)
	at com.vaticle.typedb.studio.framework.graph.BackgroundTask$launch$2.invoke(BackgroundTask.kt:30)
	at com.vaticle.typedb.studio.framework.graph.BackgroundTask$launch$2.invoke(BackgroundTask.kt:28)
	at androidx.compose.runtime.MonotonicFrameClockKt$withFrameMillis$2.invoke(MonotonicFrameClock.kt:66)
	at androidx.compose.runtime.MonotonicFrameClockKt$withFrameMillis$2.invoke(MonotonicFrameClock.kt:66)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:461)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:414)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:326)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:325)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:109)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:87)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:325)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:510)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:50)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at (Coroutine boundary.()
	at com.vaticle.typedb.studio.framework.graph.BackgroundTask.launch(BackgroundTask.kt:28)
	at com.vaticle.typedb.studio.framework.graph.GraphArea$Layout$4.invokeSuspend(GraphArea.kt:84)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at com.vaticle.typedb.studio.framework.graph.Viewport.nearestEdges-k-4lQ0M(Viewport.kt:177)
	at com.vaticle.typedb.studio.framework.graph.Viewport.findEdgeAt-3MmeM6k(Viewport.kt:101)
	at com.vaticle.typedb.studio.framework.graph.Interactions$HoveredObjectChecker.run(Interactions.kt:82)
	at com.vaticle.typedb.studio.framework.graph.BackgroundTask$launch$2.invoke(BackgroundTask.kt:30)
	at com.vaticle.typedb.studio.framework.graph.BackgroundTask$launch$2.invoke(BackgroundTask.kt:28)
	at androidx.compose.runtime.MonotonicFrameClockKt$withFrameMillis$2.invoke(MonotonicFrameClock.kt:66)
	at androidx.compose.runtime.MonotonicFrameClockKt$withFrameMillis$2.invoke(MonotonicFrameClock.kt:66)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:461)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:414)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:326)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:325)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:109)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:87)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:325)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:510)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:50)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Environment

1. TypeDB version: Cluster 2.20.0
2. OS of TypeDB server: TypeDB Cloud AWS
3. Studio version: a7da2961e8d16b19c944ac8feae946166f0c1e51
4. OS of Studio: MacOS 12.6.1

**Comment by alexjpwalker** [comment]
Fixed in Studio 3 due to no Java.
